openapi: 3.0.0
info:
  title: Expense Tracker API
  version: 1.0.0

paths:
  /expense-tracker-api/public/index.php/api/v1/signup:
    post:
      tags:
        - Register a User
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: John
                password:
                  type: string
                  example: Johndoe123#
        required: true
      responses:
        '200':
          description: User registered successfully !
          content:
            application/json:
              schema:
                type: object
                properties:
                  '200':
                    type: string
                    example: User registered successfully !
        '400':
          description: User John already exist !
          content: 
            application/json:
              schema:
                type: object
                properties:
                  '400':
                    type: string
                    example: User John already exist !